### ISSUE TITLE
not working with jQuery 1.10.1

### ISSUE THREAD

**Issue by agispas** [vonKristoff/Shards#3]
I'm trying to use this plugin with jQuery 1.10.1 but it doesnt work. 
This is what I'm getting inside the console: 

`Uncaught TypeError: Cannot read property 'webkit' of undefined`

**Comment by vonKristoff** [comment]
Hey - yeah i never tested it with anything > jquery 1.7.1 ... the reason being is that this plugin does its own CSS prefixing - as does jquery 1.8 and above - resulting in them conflicting. If u can - downgrade your jquery.

**Comment by agispas** [comment]
I can not really downgrade jQuery because I'm using Bootstrap framework. 
Do you have any tips on how can I make it work with the latest version?
I think this will help a lot of people because the majority are using the latest versions of jQuery. 
Thanks!

**Comment by vonKristoff** [comment]
Unfortunatey - the whole way shards works is based on the webkit linear
gradient .. and browsers are changing the way they deploy gradients now
whilst it becomes standardised -> see here
http://css-tricks.com/css3-gradients/

Meaning the whole thing would be need to be redeveloped to advance forward
anyhow, let alone 'just work' with later versions of jquery. jQuery is
becoming fatter and fatter in its latest carnations, and I doubt these
versions really are the number 1 choice of web developers, as there are
numerous other better libraires that can be moduled together within the
stack to create the perfect mix of resources for the modern dev workflow.

This was just a toy for its time anyhow! Sorry if you cannot make it fit
for your project. You could always <iframe> it in however - as my
suggestive hack to work with your bootstrap.

On 17 April 2014 11:25, dynamyc notifications@github.com wrote:

> I can not really downgrade jquery because I'm using Bootstrap framework.
> Do you have any tips on how can I make it work with the latest version?
> I think this will help a lot of people because the majority are using the
> latest versions of jQuery.
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vonKristoff/Shards/issues/3#issuecomment-40700634
> .

## 

best,
Jean-Christophe Nicolas ../
